# Generated by Django 4.0.3 on 2022-04-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurupedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blackhole.png', upload_to=''),
        ),
    ]
